import Head from 'next/head'
import { useEffect } from 'react';
import styles from '../styles/Home.module.css'

export default function Home({ }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        asd
      </div>
    </div>
  )
}


// export async function getServerSideProps() {
//   // Fetch data from external API
//   const res = await fetch(`http://localhost:3000/api/user/getUsers`)
//   console.log(res)
//   // const data = await res.json()

//   // Pass data to the page via props
//   // return { props: { data } }
// }